version: "3.8"
services:
  list:
    build: .
    ports:
      - "7979:7979"  # Port 7979 für den List-Service
    environment:
      - SERVER_PORT=7979
      - DATASET_SERVICE_URL=http://host.docker.internal:8080/v1/dataset  # URL für den Dataset-Dienst
      - RESULT_SERVICE_URL=http://host.docker.internal:8080/v1/result  # URL für den Dataset-Dienst
    networks:
      - example
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7979/getCustomers || exit 1"]
      interval: 2s
      timeout: 5s
      start_period: 2s
      retries: 5

  curl:
    image: curlimages/curl
    depends_on:
      list:
        condition: service_healthy
    networks:
      - example
    command: >
      sh -c "
        echo 'Executing GET request...';
        curl -L -v http://list:7979/getCustomers &&
        echo 'Executing POST request...' &&
        curl -X POST -L -v http://list:7979/postCustomerData
      "

networks:
  example:
    driver: bridge
